src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull()
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThanOrEqual("today UTC",
     *     message="La date de début doit être supérieure ou égale à la date du jour!")
     * @Assert\Expression("this.getDateStart() <= this.getDateEnd()",
     *     message="La date de début doit être inférieure ou égale à la date de fin!"
     * )
     */
    private $date_start;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThanOrEqual("today UTC",
     *     message="La date de fin doit être supérieure ou égale à la date du jour!")
     * @Assert\Expression(
     *     "this.getDateEnd() >= this.getDateStart()",
     *     message="La date de fin doit être supérieure ou égale à la date de début!"
     * )
     */
    private $date_end;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull()
     * @Assert\NotBlank()
     */
    private $location;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *      min = 10,
     *      max = 500,
     *      minMessage = "Votre description doit contenir au moins 10 caractères",
     *      maxMessage = "Votre description doit contenir au plus 500 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Il doit y avoir au moins un participant")
     */
    private $nb_participants;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated_at;
    
    /**
     * @ORM\ManyToMany(targetEntity=Restriction::class, inversedBy="events")
     */
    private $restrictions;

    /**
     * @ORM\Column(type="float")
     * @Assert\PositiveOrZero
     */
    private $price;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Gedmo\Timestampable(on="change", field={"status"})
     */
    private $updatedStatus;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="events")
     */
    private $participants;


    /**
     * Event constructor.
     */
    public function __construct()
    {
        $this->restrictions = new ArrayCollection();
        $this->participants = new ArrayCollection();
    }


    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @param string $slug
     * @return $this
     */
    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    /**
     * @param \DateTimeInterface $date_start
     * @return $this
     */
    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    /**
     * @param \DateTimeInterface $date_end
     * @return $this
     */
    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @param string $status
     * @return $this
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * @param string $location
     * @return $this
     */
    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return $this
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getNbParticipants(): ?int
    {
        return $this->nb_participants;
    }

    /**
     * @param int $nb_participants
     * @return $this
     */
    public function setNbParticipants(int $nb_participants): self
    {
        $this->nb_participants = $nb_participants;

        return $this;
    }

    /**
     * @return User|null
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User $user
     * @return $this
     */
    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    /*public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }*/

    /**
     * @return \DateTimeInterface|null
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    /*public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }*/

    /**
     * @return Collection|Restriction[]
     */
    public function getRestrictions(): Collection
    {
        return $this->restrictions;
    }

    /**
     * @param Restriction $restriction
     * @return $this
     */
    public function addRestriction(Restriction $restriction): self
    {
        if (!$this->restrictions->contains($restriction)) {
            $this->restrictions[] = $restriction;
        }

        return $this;
    }

    /**
     * @param Restriction $restriction
     * @return $this
     */
    public function removeRestriction(Restriction $restriction): self
    {
        $this->restrictions->removeElement($restriction);

        return $this;
    }

    /**
     * @return float|null
     */
    public function getPrice(): ?float
    {
        return $this->price;
    }

    /**
     * @param float $price
     * @return $this
     */
    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getUpdatedStatus(): ?\DateTimeInterface
    {
        return $this->updatedStatus;
    }

    public function setUpdatedStatus(?\DateTimeInterface $updatedStatus): self
    {
        $this->updatedStatus = $updatedStatus;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(User $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
        }

        return $this;
    }

    public function removeParticipant(User $participant): self
    {
        $this->participants->removeElement($participant);

        return $this;
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use App\Repository\UserRepository;
use Eluceo\iCal\Component\Calendar;
use Eluceo\iCal\Component\Event as ICalEvent;
use Eluceo\iCal\Property\Event\Geo;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\HttpClient\Exception\ClientExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\RedirectionExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\ServerExceptionInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;

/**
 * @Route("/dashboard/events")
 */
class EventController extends AbstractController
{
    /**
     * @Route("/", name="event_index", methods={"GET"})
     * @param EventRepository $eventRepository
     * @return Response
     */
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findNext10DaysEvents()
        ]);
    }

    /**
     * @Route("/new", name="event_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $event->setUser($this->getUser());
            $event->setStatus("Open");

            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/past",name="past_event")
     * @param EventRepository $eventRepository
     * @return Response
     */
    public function pastEvents(EventRepository $eventRepository): Response
    {
        return $this->render('event/pasts.html.twig', [
            'events' => $eventRepository->getPastEvents($this->getUser()),
        ]);
    }

    /**
     * @Route("/actual",name="actual_event")
     * @param EventRepository $eventRepository
     * @return Response
     */
    public function actualEvents(EventRepository $eventRepository): Response
    {
        return $this->render('event/actual.html.twig', [
            'events' => $eventRepository->getActualEvents($this->getUser()),
        ]);
    }

    public function inCommingEvents()
    {

    }

    /**
     * @Route("/{id}", name="event_show", methods={"GET"})
     * @param Event $event
     * @return Response
     */
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event
        ]);
    }

    /**
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Event $event
     * @return Response
     */
    public function edit(Request $request, Event $event): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     * @param Request $request
     * @param Event $event
     * @return Response
     */
    public function delete(Request $request, Event $event): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }

    /**
     * @Route("/reserve/{id}", name="event_reserve", methods={"GET"})
     * @param Event $event
     * @return RedirectResponse
     */
    public function reserve(Event $event): RedirectResponse
    {
        $event->addParticipant($this->getUser());
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->flush();
        return $this->redirectToRoute('event_index');
    }

    /**
     * @Route("/desiste/{id}", name="event_desiste")
     * @param Event $event
     * @return RedirectResponse
     */
    public function desiste(Event $event): RedirectResponse
    {
        $event->removeParticipant($this->getUser());
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->flush();
        return $this->redirectToRoute('event_index');
    }

    /**
     * @Route("/remove_reservation/{id}/{id_user}", name="event_remove_participant")
     * @param UserRepository $userRepository
     * @param Event $event
     * @param int|null $id_user
     * @return RedirectResponse
     */
    public function removeReservation(UserRepository $userRepository, Event $event, ?int $id_user): RedirectResponse
    {
        $user = $userRepository->find($id_user);
        $event->removeParticipant($user);
        $em = $this->getDoctrine()->getManager();
        $em->flush();
        return $this->redirectToRoute('event_show', ['id' => $event->getId()]);
    }

    /**
     * @Route("/add_calendar/{id}",name="add_calendar", methods={"GET"})
     * @param Event $event
     * @param HttpClientInterface $client
     */
    public function addCalendar(Event $event, HttpClientInterface $client)
    {
        $vCalendar = new Calendar('13123');
        $iCalEvent = new ICalEvent();

        $iCalEvent->setSummary($event->getName());
        $iCalEvent->setDescription($event->getDescription());
        $iCalEvent->setDtStart($event->getDateStart());
        $iCalEvent->setDtEnd($event->getDateEnd());
        $vCalendar->addComponent($iCalEvent);

        header('Content-Type: text/calendar; charset=utf-8');
        header('Content-Disposition: inline; filename="cal.ics"');
        echo($vCalendar->render());
        exit;
    }

    /**
     * @Route("/stats",name="events_stats", methods={"GET"})
     */
    public function stats()
    {
        return $this->render('event/stats.html.twig', []);
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/event/actual.html.twig
{% extends 'base-dashboard.html.twig' %}

{% block subtitle %}Evenements dans le passé{% endblock %}

{% block content %}

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Date de l'evenement</th>
            <th>Nombre de participants</th>
        </tr>
        </thead>
        <tbody>
        {% for event in events %}
            <tr>
                <td>{{ event.name }}</td>
                <td>{{ event.datestart|date('d/m/Y') }}</td>
                <td>{{ event.participants|length }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('event_index') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block subtitle %}Evenements à + 10 jours{% endblock %}

{% block body %}
    {% for event in events %}
        <h1>Les Evenements de {{ event.getUser().getFirstName() }}
            {{ event.getUser().getLastName() }}</h1>

        <table class="table">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Date/Heure de début</th>
            <th>Date/Heure de fin</th>
            <th>Lieu</th>
            <th>Description</th>
            <th>Places restantes</th>
            <th>Prix</th>
            <th>Status</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>

        <tr>
            <td>{{ event.name }}</td>
            <td>{{ event.dateStart ? event.dateStart|date('d/m/Y H:i') : '' }}</td>
            <td>{{ event.dateEnd ? event.dateEnd|date('d/m/Y H:i') : '' }}</td>
            <td><a target="_blank"
                   href="https://maps.google.fr/?q={{ event.location|replace({' ':'+'}) }}">{{ event.location }}</a>
            </td>
            <td>{{ event.description|nl2br }}</td>
            <td>{{ event.nbParticipants - event.participants|length }}</td>
            <td>{{ event.price }} €</td>
            <td>{{ event.status }}</td>
            <td>
                {% if  event.user != app.user %}
                    {% if app.user in event.participants %}
                        <a href="{{ path('add_calendar',{id: event.id}) }}">Ajouter au calendrier</a>
                        <a href="{{ path('event_desiste',{id: event.id}) }}" class="btn btn-outline-danger">Se
                            désister</a>
                    {% else %}
                        {% if event.nbParticipants - event.participants|length > 0 %}
                            <a href="{{ path('event_reserve',{id: event.id}) }}" class="btn btn-outline-primary">Reserver
                                sa
                                place</a>
                        {% endif %}
                    {% endif %}
                {% endif %}
                <a href="{{ path('event_show', {'id': event.id}) }}">show</a>
                <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="13">no records found</td>
        </tr>

        </tbody>
        </table>

        <a href="{{ path('event_new') }}">Create new</a>
    {% endfor %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

templates/event/new.html.twig
{% extends 'base-dashboard.html.twig' %}

{% block title %}New Event{% endblock %}

{% block content %}
    <h1>Créer un nouvel évènement</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('event_index') }}">back to list</a>
{% endblock %}

templates/event/pasts.html.twig
{% extends 'base-dashboard.html.twig' %}

{% block subtitle %}Evenements dans le passé{% endblock %}

{% block content %}

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Nom</th>
            <th>Date de l'evenement</th>
            <th>Nombre de participants</th>
        </tr>
        </thead>
        <tbody>
        {% for event in events %}
            <tr>
                <td>{{ event.name }}</td>
                <td>{{ event.datestart|date('d/m/Y') }}</td>
                <td>{{ event.participants|length }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1>Evenement {{ event.getName() }}</h1>

    <table class="table">
        <tbody>

        <tr>
            <th>Nom</th>
            <td>{{ event.name }}</td>

        <tr>
            <th>Date/Heure de début</th>
            <td>{{ event.dateStart ? event.dateStart|date('d/m/Y H:i') : '' }}</td>
        </tr>
        <tr>
            <th>Date/Heure de fin</th>
            <td>{{ event.dateEnd ? event.dateEnd|date('d/m/Y H:i') : '' }}</td>
        </tr>

        <tr>
            <th>Lieu</th>
            <td>{{ event.location }}</td>
        </tr>
        <tr>

            <th>Description</th>
            <td>{{ event.description }}</td>
        </tr>
        <tr>
            <th>Capacité</th>
            <td>{{ event.nbParticipants }}</td>
        </tr>

        <tr>
            <th>Prix</th>
            <td>{{ event.price }} €</td>
        </tr>

        <tr>
            <th>Restriction(s)</th>
            {% for resctriction in event.restrictions %}
                <td>{{ resctriction.getName() }},</td>
            {% endfor %}
        </tr>

        <tr>
            <th>Status</th>
            <td>{{ event.status }}</td>
        </tr>

        </tbody>
    </table>

    {% if event.user == app.user %}
        <hr>
        <h2>Liste des participants</h2>
        <table>
            <thead>
            <tr>
                <th>Nom Prénom</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for participant in event.participants %}
                <tr>
                    <td>{{ participant.firstname|capitalize }} {{ participant.lastname|upper }}</td>
                    <td><a href="{{ path('event_remove_participant', {id:event.id, id_user: participant.id }) }}">Supprimer la
                            réservation</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

    <a href="{{ path('event_index') }}">back to list</a>

    <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}